# Generated by Django 4.0.5 on 2022-06-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[], default='', max_length=20)),
                ('catagory', models.CharField(choices=[], default='', max_length=20)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
