# Generated by Django 4.0.5 on 2022-06-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
